spring:
  application:
    name: spring-boot-dubbo-demo-provider
  main:
    allow-bean-definition-overriding: true # 不设置会与Spring Boot冲突
server:
  port: 8888
dubbo:
  scan:
    base-packages: com.yanle.springboot.dubbo.demo.service
  protocol:
    name: dubbo
    port: -1
  metadata-report:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
demo:
  service:
    version: 0.0.1 # 消费者版本与生产者版本一致
embedded:
  zookeeper:
    port: 2181

